permalink: /posts/:year/:month/:day/:title.html

exclude:
- .ruby-version
- .ruby-gemset
- Gemfile
- Gemfile.lock
- README.md
- CNAME
- package.json
- package-lock.json
- node_modules/
- build.js
- assets/javascripts/main.src.js
- cache/
- script/
- vendor/

markdown: kramdown
highlighter: rouge
title: Latchezar Tzvetkoff
subtitle: A nerd's personal archive
production_url: http://tzvetkoff.net

sass:
  style: compressed
  sass_dir: assets/stylesheets

author:
  name: Latchezar Tzvetkoff
  email: latchezar&lt;foo&gt;tzvetkoff&lt;bar&gt;net
  github: tzvetkoff
  twitter: tzvetkoff
  facebook: tzvetkoff

disqus:
  shortname: tzvetkoff
